// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutUploader: typeof import('./components/AboutUploader.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PostCard: typeof import('./components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar/index.vue')['default']
    SidebarDiscover: typeof import('./components/Sidebar/SidebarDiscover.vue')['default']
    SidebarFooter: typeof import('./components/Sidebar/SidebarFooter.vue')['default']
    SidebarSuggestedAcc: typeof import('./components/Sidebar/SidebarSuggestedAcc.vue')['default']
    TailwindLoader: typeof import('./components/TailwindLoader.vue')['default']
    VideoCard: typeof import('./components/VideoCard.vue')['default']
    VideoComments: typeof import('./components/VideoComments.vue')['default']
  }
}
